"""empty message

Revision ID: 752f1069bace
Revises: fe694018b0e1
Create Date: 2023-09-20 21:33:41.604329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '752f1069bace'
down_revision: Union[str, None] = 'fe694018b0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loggedbenchmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enum', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('loggedexercise', 'created_datetime',
               existing_type=sa.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loggedexercise', 'created_datetime',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_table('loggedbenchmark')
    # ### end Alembic commands ###
