"""empty message

Revision ID: dd22063fdeff
Revises: 
Create Date: 2023-10-04 15:57:41.204978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dd22063fdeff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loggedbenchmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enum', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loggedexercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enum', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loggedexercise')
    op.drop_table('loggedbenchmark')
    # ### end Alembic commands ###
